name: .NET build and test
env:
  CURRENT_VERSION: 1.0.${{ github.run_number }}
  LAST_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Fiddeling with secrets
      env: 
          NUGET_TOKEN_EXISTS: ${{ secrets.NUGET_TOKEN }}
      if:  env.NUGET_TOKEN_EXISTS != ''
      run: echo "NUGET_TOKEN_EXISTS exists - implementation of secret checking working on all runners"
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release

  windows-wsl-ubuntu-22_04:
    name: WSL [Ubuntu 22.04]
    runs-on: windows-latest
    defaults:
      run:
        shell: wsl-bash {0} # https://github.com/marketplace/actions/setup-wsl#default-shell
    steps:
    - uses: actions/checkout@v3
    - uses: Vampire/setup-wsl@v1
      with:
        distribution: Ubuntu-22.04
    - name: Nvm
      run: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash
    - name: Dependencies
      run: |
        pwd # DEBUG
        ls # DEBUG
        sudo apt update
        sudo apt install dotnet6 zip -y
        dotnet test --configuration Release
  
  deployRelease:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [build, windows-wsl-ubuntu-22_04]
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: NugetPush
      env: 
          NUGET_TOKEN_EXISTS: ${{ secrets.NUGET_TOKEN }}
      if:  env.NUGET_TOKEN_EXISTS != ''
      run: |
          ls ./GithubActionsHelloWorld/bin/Release
          dotnet nuget push ./GithubActionsHelloWorld/bin/Release/*.nupkg --skip-duplicate --api-key ${{secrets.NUGET_TOKEN}} --source https://apiint.nugettest.org/v3/index.json
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ env.CURRENT_VERSION }}"
        prerelease: false
        title: "Release ${{ env.CURRENT_VERSION }}"
        files: |
          ./GithubActionsHelloWorld/bin/Release/*.nupkg
          ./GithubActionsHelloWorld/bin/Release/*.snupkg

  deployTest:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [build, windows-wsl-ubuntu-22_04]
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: NugetPush
      env:
          NUGET_TOKEN_EXISTS: ${{ secrets.NUGET_TEST_TOKEN }}
      if:  env.NUGET_TOKEN_EXISTS != ''
      run: |
          ls ./GithubActionsHelloWorld/bin/Release
          dotnet nuget push ./GithubActionsHelloWorld/bin/Release/*.nupkg --skip-duplicate --api-key ${{secrets.NUGET_TEST_TOKEN}} --source https://apiint.nugettest.org/v3/index.json
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ env.CURRENT_VERSION }}"
        prerelease: true
        title: "Prerelease Build ${{ env.CURRENT_VERSION }}"
        files: |
          ./GithubActionsHelloWorld/bin/Release/*.nupkg
          ./GithubActionsHelloWorld/bin/Release/*.snupkg

