name: .NET build and test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
    - name: "Build & test"
      run: |
          echo "done!"
          pwd

  deployMain:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build 
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish
      run: dotnet publish --configuration Release --no-restore
    - name: NugetPush
      run: |
          ls ./GithubActionsHelloWorld/bin/Release
          dotnet nuget push ./GithubActionsHelloWorld/bin/Release/*.nupkg --skip-duplicate --api-key ${{secrets.NUGET_TOKEN}} --source https://int.nugettest.org/
          dotnet nuget push ./GithubActionsHelloWorld/bin/Release/*.snupkg --skip-duplicate --api-key ${{secrets.NUGET_TOKEN}} --source https://int.nugettest.org/
    - uses: papeloto/action-zip@v1
      with:
          files: ./GithubActionsHelloWorld/bin/Release/net6.0/publish/
          dest: GithubActionsHelloWorld.zip
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        title: "Release Build"
        files: |
          LICENSE
          GithubActionsHelloWorld.zip

  deployTest:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build 
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish
      run: dotnet publish --configuration Release --no-restore
    - name: NugetPush
      run: |
          ls ./GithubActionsHelloWorld/bin/Release
          dotnet nuget push ./GithubActionsHelloWorld/bin/Release/*.nupkg --skip-duplicate --api-key ${{secrets.NUGET_TOKEN}} --source https://int.nugettest.org/
          dotnet nuget push ./GithubActionsHelloWorld/bin/Release/*.snupkg --skip-duplicate --api-key ${{secrets.NUGET_TOKEN}} --source https://int.nugettest.org/
    - uses: papeloto/action-zip@v1
      with:
          files: ./GithubActionsHelloWorld/bin/Release/net6.0/publish/
          dest: GithubActionsHelloWorld.zip
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest-prerelease"
        prerelease: true
        title: "Development Build"
        files: |
          LICENSE
          GithubActionsHelloWorld.zip
