name: .NET

on:
  push:
    branches: [ main, automated-nuget.org-publish ]
  pull_request:
    branches: [ main, automated-nuget.org-publish ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
    - name: "Build & test"
      run: |
          echo "done!"
          pwd

  publish:
    runs-on: ubuntu-latest
    needs: build 
    steps:
    - name: Bump version
      id: package_version
      uses: KageKirin/bump-csproj-version@v0
      with:
        file: GithubActionsHelloWorld/GithubActionsHelloWorld.csproj
        patch: true

    - name: Commit new version
      run: |
        git commit -am "CI: bump version to ${{ steps.test.package_version.version }}"
        git tag -m "CI: create new tag" v${{ steps.test.package_version.version }}
        git push --follow-tags https://${{ github.token }}@github.com/OWNER/REPO
        
    - name: Publish
      run: dotnet publish --configuration Release --no-restore
    - uses: papeloto/action-zip@v1
      with:
          files: ./GithubActionsHelloWorld/bin/Release/net6.0/publish/
          dest: GithubActionsHelloWorld.zip
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          LICENSE
          GithubActionsHelloWorld.zip
          #https://int.nugettest.org/
