name: .NET build and test
env:
  CURRENT_VERSION: 1.0.${{ github.run_number }}
  LAST_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
  NUGET_TOKEN_EXISTS: ${{ secrets.NUGET_TOKEN }}
  NUGET_TOKEN_TEST_EXISTS: ${{ secrets.NUGET_TEST_TOKEN }}

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Fiddeling with secrets
      if:  secrets.NUGET_TOKEN != ''
      run: echo "secrets.NUGET_TOKEN exists - implementation of secret checking working on all runners"
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release

  deployRelease:
    if: github.ref == 'refs/heads/main' && secrets.NUGET_TOKEN != ''
    runs-on: ubuntu-latest
    needs: build 
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: NugetPush
      run: |
          ls ./GithubActionsHelloWorld/bin/Release
          dotnet nuget push ./GithubActionsHelloWorld/bin/Release/*.nupkg --skip-duplicate --api-key ${{secrets.NUGET_TOKEN}} --source https://apiint.nugettest.org/v3/index.json
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ env.CURRENT_VERSION }}"
        prerelease: false
        title: "Release ${{ env.CURRENT_VERSION }}"
        files: |
          ./GithubActionsHelloWorld/bin/Release/*.nupkg
          ./GithubActionsHelloWorld/bin/Release/*.snupkg

  deployTest:
    if: github.ref != 'refs/heads/main' && secrets.NUGET_TEST_TOKEN != ''
    runs-on: ubuntu-latest
    needs: build 
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: NugetPush
      run: |
          ls ./GithubActionsHelloWorld/bin/Release
          dotnet nuget push ./GithubActionsHelloWorld/bin/Release/*.nupkg --skip-duplicate --api-key ${{secrets.NUGET_TEST_TOKEN}} --source https://apiint.nugettest.org/v3/index.json
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ env.CURRENT_VERSION }}"
        prerelease: true
        title: "Prerelease Build ${{ env.CURRENT_VERSION }}"
        files: |
          ./GithubActionsHelloWorld/bin/Release/*.nupkg
          ./GithubActionsHelloWorld/bin/Release/*.snupkg

